# Generated by Django 5.1.1 on 2024-10-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Created_Date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='Published_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
